---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-analyzer
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: log-analyzer
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
rules:
  # Conjur secrets provider: čtení a zápis do K8s Secret
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "patch", "update"]
    resourceNames: ["{{ .Values.app.secretName }}"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: log-analyzer
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: log-analyzer
subjects:
  - kind: ServiceAccount
    name: log-analyzer
    namespace: {{ .Values.namespace }}
